#!/bin/bash

# Installing Dependencies
echo "#####################################"
echo "Installing Dependencies"
echo "#####################################"
sudo yum install wget httpd unzip -y > /dev/null
echo

# Start and enable the service
echo "#####################################"
echo "Start and Enable HTTPD service"
echo "#####################################"
sudo systemctl start httpd
sudo systemctl enable httpd
echo

# Creating temporary directory
echo "#####################################"
echo "Starting Artifact deployment"
echo "#####################################"
mkdir -p /tmp/webfiles
cd /tmp/webfiles
echo

wget https://www.tooplate.com/zip-templates/2131_wedding_lite.zip > /dev/null
unzip 2131_wedding_lite.zip
sudo cp -r 2131_wedding_lite/* /var/www/html/
echo

# Bounce Service
echo "#####################################"
echo "Restarting HTTPD server"
echo "#####################################"
systemctl restart httpd
echo

# Clean Up
echo "Removing Temporary files"
rm -rf /tmp/webfiles
echo
