#!/bin/bash

read -p 'Enter a Number:' num
echo 

if [ $num -gt 100 ]
then
  echo "We have entered in IF block"
  sleep 3
  echo "$num is great than 100"
elif [ $num -lt 100 ]
then
  echo "Number is less than 100"
else
  echo "Number is equal to 100"
fi
